input:
  - key: wikidata
    src:
      - host: .*
        dir: 'src/main/resources/sample/demo'
    filter: |-
      wikidata.txt
#handlers:
#  - pattern: .*(wikidata).*
#    handler: delimHandlerHash
job_sets:
  - name: db_fill
    jobs:
      - databaseFiller2
